### ISSUE TITLE
RW example

### ISSUE THREAD

**Issue by syphernl** [benkonrath/transip-api#10]
Hi! I'd like to build upon this but it only implements RO calls but I want to make RW calls (e.g. to update the DNS). I have been fiddling around with it but it always throws an invalid signature.

Do you have any examples on how to deal with RW calls?

**Comment by roaldnefs** [comment]
An example of a RW call can be found in PR #30.

@benkonrath, this seems like a very old issue that might be closed.

**Comment by benkonrath** [comment]
Yep, thanks.
