### ISSUE TITLE
release 0.4.0 introduces a breaking interface change should this not have been a major semver update ?

### ISSUE THREAD

**Issue by AubreyHewes** [benkonrath/transip-api#27]
First up; Thanks for the API !!

I have one gripe/question with release 0.4.0...

People tend to have used the requirement as `transip>=0.3.0` this should ensure that major changes (i.e. interface changes) are not affected. 

`0.4.0` introduces a breaking interface change https://github.com/benkonrath/transip-api/commit/f8bb242dec057578ae1f832846364e191deb9caf by renaming `transip.service.dns` to `transip.service.objects`. Surely this should have been a major update?

**Comment by benkonrath** [comment]
Thanks for your feedback. As far as I understand things, semver offers no guarantees for 0.x.x versions and I didn't want to release 1.0.0 yet. The idea is, if you had to follow semver during initial development, you'd need to do a 1.0 release fairly early in your development process. If I ever make a 1.0 release, that's when I'll start using semver and bumping the major version for incompatible changes.

I realize it's a bit of a pain to do an update like this, but the starting 0 in the 0.4.0 is meant to tell users that things could still change.

> People tend to have used the requirement as `transip>=0.3.0` this should ensure that major changes (i.e. interface changes) are not affected.

This is a bad practice. You should pin your dependencies to specific version. Even if I did release 1.0.0, users having `transip>=0.3.0` would still get the broken version. But I get your point,  maybe you mean users do something like this: `transip>=0.3.0,<1.0.0`. But instead I'd recommend something like this:  `transip>=0.3.0,<0.4.0` - this way I'd get the 0.3.x releases and but not the 0.4.0 and above. 

I hope this helps to explain my reasoning behind the release number.

**Comment by AubreyHewes** [comment]
@benkonrath I understand where you are coming from, but I do not agree. We will leave it as that ;-)

Interface changes are major. So require a major update. Else do not change the interface. If the package is in flux use labels (alpha/beta/etc i.e. 0.4.0-beta.0). This alleviates updating the major, and ensures downstream parties will not get a breaking version. Try on http://jubianchi.github.io/semver-check/

The idea of semver is that you can _safely update within the major_ (no breaking api).  So `transip>=0.3.0` _should always_ be safe (no breaking api). 

Your proposal limits possible forward integration by requiring downstream to explicitly require a version. I understand this I just don't agree ;-)

On the other hand I agree your library is your own and you can decide how you do this. It is just other libraries use your library and they expect that semver is followed. 

https://semver.org

> MAJOR version when you make incompatible API changes,
> MINOR version when you add functionality in a backwards-compatible manner, and
> PATCH version when you make backwards-compatible bug fixes.
Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.
